docker, db 설정 및 schema 구현
f-lab-edu/one-way-ticket pull request #4
Opened 2024-12-03 16:13 UTC by SEONGHUN-95

1. Docker compose를 이용하여 Spring 서버와 mysql을 컨테이너화하였습니다.
2. 코드 실행시 JPA에 의해 정의되던 엔티티를  schema.sql 파일을 통해 정의하는 것으로 변경하였습니다.
3. 서버 내 계층간 이동에서는 Dto 사용 대신 객체를 반환하고 클라이언트로 전송 시에만 Dto를 사용하는 것으로 수정하였습니다.
4. Entity, Controller에 있었던 메서드, 로직들을 서비스 레이어로 옮기거나 수정하였습니다.
5. Dto, PathVariable 등에서 값 유효성 검증을 하고, 서비스 레이어에서는 전역 예외처리를 통해 상황별로 예외 발생 이유를 명확히 하려 하였습니다.

2024-12-04 00:57 UTC, f-lab-lyan commented on api/application.yml
> -    url: jdbc:mysql://localhost:3306/my-db
이렇게 바꾸면, 로컬환경에서는 DB에 접근을 못하게 되지 않을까요?

2024-12-04 00:59 UTC, f-lab-lyan commented on api/schema.sql
이 파일은 위치를 resource밑으로 옮기는게 좋을 것 같아요.

2024-12-04 01:01 UTC, f-lab-lyan commented on api/schema.sql
쿼리가 실행되는 조건도 변경할 필요가 있어보입니다.

2024-12-04 01:04 UTC, f-lab-lyan commented on Dockerfile
> +ARG JAR_FILE=build/libs/*.jar
jar 파일의 위치가 정확하지 않은 것 같습니다.

2024-12-04 01:10 UTC, f-lab-lyan commented on Dockerfile
https://docs.docker.com/build/building/multi-stage/

2024-12-04 01:21 UTC, f-lab-lyan commented on api/src/main/java/org/onewayticket/repository/FlightRepository.java
```suggestion
```

2024-12-04 01:24 UTC, f-lab-lyan commented on api/src/main/java/org/onewayticket/service/BookingService.java
> +    public String generateToken(String reservationNumber, String email) {
조금 더 간략한 버전을 제공할 수 있지 않을까요?

2024-12-04 01:27 UTC, f-lab-lyan commented on api/src/test/java/org/onewayticket/controller/FlightControllerIntegrationTest.java
> +@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2, replace = AutoConfigureTestDatabase.Replace.ANY)
어떤 설정인지 확인하고 넘어가면 좋을 것 같습니다.

2024-12-04 01:27 UTC, f-lab-lyan commented on api/src/test/java/org/onewayticket/controller/FlightControllerIntegrationTest.java
> +import org.springframework.test.context.ActiveProfiles;
필요없는 import인 것 같네요. :-)

2024-12-04 01:40 UTC, f-lab-lyan commented on api/src/test/java/org/onewayticket/service/BookingServiceTest.java
> +        String token = bookingService.generateToken(booking.getReferenceCode(), booking.getBookingEmail());
https://www.baeldung.com/mockito-spy

2024-12-04 01:43 UTC, f-lab-lyan commented on docker-compose.yml
> +networks:
네트웍 셋팅을 안하면, 안되는 것인가요?

2024-12-04 01:44 UTC, f-lab-lyan requested changes
- Dockerfile 수정
- docker-compose도 수정
- 커멘트 반영

2024-12-10 12:51 UTC, SEONGHUN-95 commented
1. 회원가입, 로그인 기능을 추가하였습니다.
- SpringSecurity 없이 JwtUtil을 만들어서 구현하였습니다.
- JwtUtil에 대한 의존도가 높아져 필터나 다른 방안들을 고민해보겠습니다.
- OAuth도 추가해보겠습니다.

2. 항공권 찜 기능, 마이 페이지 기능을 추가하였습니다.

2024-12-11 01:16 UTC, f-lab-lyan commented on api/src/main/java/org/onewayticket/dto/UserInfoDto.java
> +        String password
네트웍을 태우는 password에 대해서 고민해보기

2024-12-11 01:40 UTC, f-lab-lyan commented on api/src/main/java/org/onewayticket/service/MemberService.java
> +        if (member != null && member.getPassword().equals(PasswordUtil.hashPassword(password))) {
이 로직은 위에서 검증이 끝난 것 같네요.

2024-12-11 01:43 UTC, f-lab-lyan commented on api/src/main/java/org/onewayticket/security/JwtUtil.java
> +        String header = Base64.getUrlEncoder().encodeToString("{\"alg\":\"HS256\",\"typ\":\"JWT\"}".getBytes());
constant로 빼면 좋을 것 같아요.

2024-12-11 01:45 UTC, f-lab-lyan commented on api/src/main/java/org/onewayticket/security/JwtUtil.java
> +        String payload = Base64.getUrlEncoder().encodeToString(("{\"sub\":\"" + username + "\",\"exp\":" + expMillis + "}").getBytes());
성능을 높이기 위해서
- ObjectMapper...(map...)
- String.format(...)

2024-12-11 01:52 UTC, f-lab-lyan commented on api/src/main/java/org/onewayticket/service/MemberService.java
> +        if (!username.matches("^[a-zA-Z0-9]+$")) {
Validation은 많으면, 많을수록 좋은 것 같아요.

2024-12-11 02:15 UTC, f-lab-lyan commented on api/src/main/java/org/onewayticket/service/BookingService.java
> +            cancelBookingForGuest(booking, token);
Guest token과 member token의 형태를 맞춰서 비지니스로직을 최대한 비슷하게 가져가는 것이 좋지 않을까요?

2024-12-11 02:21 UTC, f-lab-lyan approved these changes
고생하셨습니다 👍

2024-12-15 06:38 UTC, merged